M48
; DRILL file KiCad 10.0.0 date 2026-04-25T02:07:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-25T02:07:32-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X150.14Y-73.5
X150.14Y-97.63
X163.74Y-73.5
X163.74Y-97.63
M30
